# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Ot9ZkOjzUZ2fc4nDvYd8nWbQczrGwHB
"""

import streamlit as st
import numpy as np
import pandas as pd
import joblib
from catboost import CatBoostRegressor
from sentence_transformers import SentenceTransformer

CURRENT_YEAR = 2026

FEATURES_V2 = [
    'car_age','kilometrage_num','km_per_year','engine_displacement_num',
    'currency_x','is_premium_segment','brand','is_dealer','is_vip','is_featured',
    'urgency_flag','trust_text_flag','ownership_flag','dealer_urgency','desc_length'
]

@st.cache_resource
def load_models():
    tab = CatBoostRegressor()
    tab.load_model("tab_model.cbm")
    meta = joblib.load("meta_ridge.pkl")
    ridge = joblib.load("ridge_sbert.pkl")
    sbert = SentenceTransformer("sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2")
    return tab, meta, ridge, sbert

tab_model, meta_model, ridge_model, sbert = load_models()

st.title("🚗 Turbo.az Price Estimator")

name = st.text_input("Car name", "Toyota Corolla")
year = st.number_input("Production year", 1960, 2026, 2015)
km = st.number_input("Mileage", 0, 1_000_000, 120000)
engine = st.number_input("Engine (L)", 0.6, 12.0, 1.6)

currency = st.selectbox("Currency", ["AZN", "$", "€"])

is_dealer = st.checkbox("Dealer")
is_vip = st.checkbox("VIP")
is_featured = st.checkbox("Featured")

urgency = st.checkbox("Urgency keywords")
trust = st.checkbox("Trust keywords")
ownership = st.checkbox("First owner keywords")

description = st.text_area("Description", "ideal veziyyetdedir tecili satilir")

if st.button("Predict price"):

    brand = name.split()[0]

    car_age = CURRENT_YEAR - year
    km_per_year = km / (car_age + 1)

    premium = 1 if currency in ["$", "€"] else 0
    dealer_urgency = 1 if (is_dealer and urgency) else 0

    X_tab = pd.DataFrame([{
        'car_age': car_age,
        'kilometrage_num': km,
        'km_per_year': km_per_year,
        'engine_displacement_num': engine,
        'currency_x': currency,
        'is_premium_segment': premium,
        'brand': brand,
        'is_dealer': int(is_dealer),
        'is_vip': int(is_vip),
        'is_featured': int(is_featured),
        'urgency_flag': int(urgency),
        'trust_text_flag': int(trust),
        'ownership_flag': int(ownership),
        'dealer_urgency': dealer_urgency,
        'desc_length': len(description)
    }])

    # Tabular prediction
    pred_tab = tab_model.predict(X_tab)[0]

    # Text embedding
    emb = sbert.encode([description], normalize_embeddings=True)
    pred_text = ridge_model.predict(emb)[0]

    # Fusion
    X_meta = np.array([[pred_tab, pred_text]])
    pred_log = meta_model.predict(X_meta)[0]

    price = np.expm1(pred_log)

    st.success(f"Estimated price: {price:,.0f} AZN")